/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c6e15b7c-2b47-4906-97ec-71504503cfab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Wqaeyh5Wr",
    "aws_user_pools_web_client_id": "408gb0pu2vpnhrasnli4ehlfuh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yzm3htvtqbdbbnm6dhf2pd2nrq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
